### ISSUE TITLE
instant cheat sheet is empty

### ISSUE THREAD

**Issue by skelter** [camsaul/lein-instant-cheatsheet#1]
I tried running instant cheat sheet on my project and it worked for a bit, but now is empty.
Is there a verbose mode I can turn on to help?

015-04-06 23:40:26.893:INFO:oejs.Server:jetty-7.6.13.v20130916
2015-04-06 23:40:26.997:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:13370
Reflection warning, clojure/core/async.clj:189:12 - reference to field incrementAndGet can't be resolved.
Reflection warning, clojure/core/async.clj:401:7 - call to method execute can't be resolved (target class is unknown).

**Comment by camsaul** [comment]
Hmmm, I'm not sure why that's happening. If you kill and restart the cheat sheet does it work again?

**Comment by skelter** [comment]
No. I've even lein clean to see if there was a local file confusing it. 

I'll try a fresh project and see if I can narrow down the cause.

**Comment by camsaul** [comment]
Great! Let me know if you find anything. If not I can add a bit of debug logging

**Comment by skelter** [comment]
I got it nailed down.

Consider

---begin core.clj
(ns asyncplay2.core
  ;(:require [clojure.core.async :as async :refer :all])
  )

(defn foo
  "I don't do a whole lot."
  [x](println x))

---end core.clj

If you uncomment the :require for core async above, then the cheatsheet comes up empty.  comment, and it comes up filled.

**Comment by camsaul** [comment]
Thanks! I'll do some investigation and figure out what's going on then push a fix

**Comment by skelter** [comment]
If I need to set up a git repo with the rudimentary project to help repro the problem, I'm willing.

**Comment by camsaul** [comment]
Try the latest version (`2.1.4`), everything should be working as expected now.

**Comment by skelter** [comment]
I see similar behavior problems with 2.1.4.

I've uploaded the test project to git@github.com:skelter/asyncplay-instant-cheat.git

**Comment by skelter** [comment]
It works great on the alpha cipher code kata!

**Comment by skelter** [comment]
I cloned lein-instant-cheatsheet; will see what I can figure out

**Comment by camsaul** [comment]
This should be fixed in the latest release.

**Comment by skelter** [comment]
whoop!  Great news!
