### ISSUE TITLE
Fails if the project defines some of the cheatsheet's resources

### ISSUE THREAD

**Issue by alexkalderimis** [camsaul/lein-instant-cheatsheet#2]
Mine is a web-project, so I have a "js/app.js" resource. My resource takes precedence over cheatsheet's when the app is loaded. Hence boom!

Suggested solution: namespace your resource folder, changing its name from "js" to "cheatsheet/js".

**Comment by camsaul** [comment]
Good call. I'll make the change

**Comment by camsaul** [comment]
Ok, fixed this in the latest version (`2.1.4`)
